language: perl
perl:
  -  "5.21"
  -  "5.20"
  -  "5.18"
  -  "5.16"
  -  "5.14"
  -  "5.12"
  -  "5.10"

# Include dependencies for all "xt/" tests.
before_install:
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n Test::Prereq

# When building, include "xt/" directory too.
script: "perl Build.PL && ./Build && prove -b -r --timer t/ xt/"
