---
name: Crypt-OpenToken
version: 0.03
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: Perl implementation of Ping Identity's "OpenToken"
license: artistic_2
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Crypt::Rijndael: 0
  Digest::HMAC_SHA1: 0
  Digest::SHA1: 0
  MIME::Base64: 0
  Moose: 0
recommends:
  Crypt::CBC: 0
  Crypt::DES_EDE3: 0
  Crypt::NULL: 0
configure_requires:
  Module::Build: 0.35
provides:
  Crypt::OpenToken:
    file: lib/Crypt/OpenToken.pm
    version: 0.03
  Crypt::OpenToken::Cipher:
    file: lib/Crypt/OpenToken/Cipher.pm
  Crypt::OpenToken::Cipher::AES128:
    file: lib/Crypt/OpenToken/Cipher/AES128.pm
  Crypt::OpenToken::Cipher::AES256:
    file: lib/Crypt/OpenToken/Cipher/AES256.pm
  Crypt::OpenToken::Cipher::DES3:
    file: lib/Crypt/OpenToken/Cipher/DES3.pm
  Crypt::OpenToken::Cipher::null:
    file: lib/Crypt/OpenToken/Cipher/null.pm
  Crypt::OpenToken::KeyGenerator:
    file: lib/Crypt/OpenToken/KeyGenerator.pm
  Crypt::OpenToken::Serializer:
    file: lib/Crypt/OpenToken/Serializer.pm
  Crypt::OpenToken::Token:
    file: lib/Crypt/OpenToken/Token.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
