---
abstract: "Perl implementation of Ping Identity's \"OpenToken\""
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenToken
provides:
  Crypt::OpenToken:
    file: lib/Crypt/OpenToken.pm
    version: 0.06
  Crypt::OpenToken::Cipher:
    file: lib/Crypt/OpenToken/Cipher.pm
    version: 0
  Crypt::OpenToken::Cipher::AES128:
    file: lib/Crypt/OpenToken/Cipher/AES128.pm
    version: 0
  Crypt::OpenToken::Cipher::AES256:
    file: lib/Crypt/OpenToken/Cipher/AES256.pm
    version: 0
  Crypt::OpenToken::Cipher::DES3:
    file: lib/Crypt/OpenToken/Cipher/DES3.pm
    version: 0
  Crypt::OpenToken::Cipher::null:
    file: lib/Crypt/OpenToken/Cipher/null.pm
    version: 0
  Crypt::OpenToken::KeyGenerator:
    file: lib/Crypt/OpenToken/KeyGenerator.pm
    version: 0
  Crypt::OpenToken::Serializer:
    file: lib/Crypt/OpenToken/Serializer.pm
    version: 0
  Crypt::OpenToken::Token:
    file: lib/Crypt/OpenToken/Token.pm
    version: 0
recommends:
  Crypt::CBC: 0
  Crypt::DES_EDE3: 0
  Crypt::NULL: 0
requires:
  Compress::Zlib: 0
  Crypt::Rijndael: 0
  Date::Parse: 0
  DateTime: 0
  Digest::HMAC_SHA1: 0
  Digest::SHA1: 0
  MIME::Base64: 0
  Moose: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.06
